name: Update Nexus Mods download counts

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Download latest binary
        run: wget "https://github.com/WardLordRuby/nexus_badges/releases/latest/download/{asset-name}" -O ./nexus-mods.gz

      - name: Decompress binary
        run: gunzip -f ./nexus-mods.gz

      - name: Run binary
        env:
          NEXUS_KEY: ${{ secrets.NEXUS_KEY }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIST_ID: ${{ vars.GIST_ID }}
          TRACKED_MODS: ${{ vars.TRACKED_MODS }}
        run: |
          chmod +x ./nexus-mods
          ./nexus-mods --remote